---
- include_tasks: packages.yml
- include_tasks: rpmfusion.yml
- include_tasks: tuxedo.yml
  when: ansible_virtualization_type == ''
- include_tasks: docker.yml
- include_tasks: golang.yml
- include_tasks: github.yml
- include_tasks: yubikey.yml
- include_tasks: ssh.yml
- include_tasks: security.yml
- include_tasks: chrome.yml
- include_tasks: vivaldi.yml
- include_tasks: nosystemd.yml
- include_tasks: dnsmasq.yml
