---
- name: Uninstall useless systemd stuff
  dnf:
    name:
      - systemd-networkd
      - systemd-resolved
    state: absent

- name: Disable useless and broken oomd
  systemd:
    name: systemd-oomd.service
    masked: yes
    enabled: no
    state: stopped
